### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by JomerDev** [TehNut/svelte-floating-ui#1]
Hello, thank you foir this library, it looks useful.
Sadly I can't import it because I always get `Uncaught ReferenceError: exports is not defined` in the browser console

**Comment by TehNut** [comment]
Hi there, sorry about that. Back when I built and published this, SvelteKit's package command for libraries wasn't great and I didn't know how to solve this. Since then, I've switched to just using FloatingUI directly so I don't really work on this package anymore.

You could instead give https://github.com/fedorovvvv/svelte-floating-ui a try, which is a copy (not a fork for some reason 🙃) of this repository that is packaged correctly.

**Comment by JomerDev** [comment]
Will do, thank you!
